name: Salaries
main: uk.servername.rahman.salaries.Salaries
version: 0.1
author: Rah
description: The description of your plugin.

commands:
  salaries:
    description: Gives his salary to a player.
    aliases: salary
    usage: |
           /<command> | Gets your salary.