name: Salaries
main: com.github.TeamRA.Salaries.Salaries
version: 0.1
author: TeamRA
description: A salary plugin giving players items.

commands:
  salaries:
    description: Gives a player his salary to a player.
    aliases: salary
    usage: |
           /<command> | Gets your salary.
    Permission: salaries.salary